Repository nerdguyahmad/randomstuff.py, pull requests merged in 2021-07, with the labels that each got.

#17 async context manager support for Client class and bug fixes
  randomstuff/client.py
  randomstuff/errors.py
  setup.py
Labels: Priority: HIGH, Type: Request

#19 type-hinting and small bug fixes
  .gitignore
  examples/jokes.py
  randomstuff/_helper.py
  randomstuff/client.py
  randomstuff/errors.py
  randomstuff/objects.py
  randomstuff/utils.py
Labels: Priority: HIGH, Status: Done, Type: Request

#20 Add weather endpoint support
  randomstuff/__init__.py
  randomstuff/ai_response.py
  randomstuff/client.py
  randomstuff/errors.py
  randomstuff/joke.py
  randomstuff/waifu.py
  randomstuff/weather.py
  setup.py
Labels: Priority: HIGH, Status: Done, Type: Request

#21 Fix version 3 AI response
  randomstuff/__init__.py
  randomstuff/client.py
  randomstuff/weather.py
  setup.py
Labels: Priority: HIGH, Type: Bug
